name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: install node
        run: sudo apt install nodejs npm 
      - name: build
        run: cd front && npm run build
      - name: bundle
        run: |
          mkdir -p app/front
          mv front/build app/front
          mv back app
      - name: upload
        run: scp -r app ${{ secrets.USER }}@${{ secrets.IP }}:/home/${{ secrets.USER }}
      - name: restart service
        run: ssh ${{ secrets.USER }}@${{ secrets.IP }} "sudo systemctl restart deemos.service"
